### ISSUE TITLE
Nest can't resolve dependencies of the APP_FILTER 

### ISSUE THREAD

**Issue by fatehMohamed14** [marciopd/nestjs-exceptions#2]
i have this error when using it;

 **Nest can't resolve dependencies of the APP_FILTER (UUID: f00cbba1-bd89-4adc-86bb-278056f4ccec) (?, Boolean, Array). Please make sure that the argument Boolean at index [0] is available in the ApplicationModule context.

 

Potential solutions:
- If Boolean is a provider, is it part of the current ApplicationModule?
- If Boolean is exported from a separate @Module, is that module imported within ApplicationModule?
  @Module({
    imports: [ /* the Module containing Boolean */ ]
  })**

here is my code: **app.module.ts**

         `import { GlobalExceptionFilter } from 'nestjs-exceptions';
         ...
         providers: [
          { provide: APP_FILTER, useClass: GlobalExceptionFilter}
         ]`

and **main.ts**

      ` const sendInternalServerErrorCause = true;
       const logAllErrors = true;
       app.useGlobalFilters(new GlobalExceptionFilter(sendInternalServerErrorCause, logAllErrors));`

**Comment by marciopd** [comment]
Hello @fatehMohamed14 , the `GlobalExceptionFilter` is not really meant to be injected by Nest.

You shouldn't need the `app.module.ts` part of your code.

Notice that in **main.ts** the filter is directly instantiated:
> app.useGlobalFilters(new GlobalExceptionFilter(sendInternalServerErrorCause, logAllErrors));
